### ISSUE TITLE
Licensing issues 2: Electric Boogaloo

### ISSUE THREAD

**Issue by gdude2002** [Cheeselab/DecoraterBot#17] opened 2016-09-01 16:59 UTC
As #11 was closed, thus signalling that a response to the comment there was clearly considered lacking in value, I felt that it was only right to create a second ticket, having done the legwork that was suggested in the closing response. So, I've audited all the dependencies (that I could find) that are being distributed from this repository, along with their licenses, and I've even summarised what it means to distribute the dependencies under those libraries. I've split the section by license below, and my recommendations are at the bottom.

**Note**: While such an audit would usually be quite expensive, I have a love for open source development and would prefer to see licenses adhered to instead of users unknowingly (or knowingly) breaking them and putting themselves at legal risk - So I've spent about two hours of my own free time working on this ticket for gratis. You're welcome.

**Note**: This audit does not cover what you'd have to do if you were distributing modified copies of the dependencies. You'll have to read up on the licenses yourselves for that - a `CTRL+F` for `distrib` should be more than enough to find what you need.

````
DISCLAIMER: I'm not a lawyer, but I have been working 
with open-source projects for over six years, and have 
come to an understanding of the common software 
licenses and how they should be applied.
```

# Python Software Foundation license

### Applicable dependencies

* Python ([x86](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/python35)) ([x64](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/python35x64)): [Link to license](https://docs.python.org/3/license.html)

### Relevant quote

> Subject to the terms and conditions of this License Agreement, PSF hereby
> grants Licensee a nonexclusive, royalty-free, world-wide license to reproduce,
> analyze, test, perform and/or display publicly, prepare derivative works,
> distribute, and otherwise use Python 3.5.2 alone or in any derivative
> version, provided, however, that **PSF's License Agreement and PSF's notice of**
> **copyright, i.e., "Copyright © 2001-2016 Python Software Foundation; All Rights**
> **Reserved" are retained in Python 3.5.2 alone or in any derivative version**
> **prepared by Licensee.**

### Simple translation

* You are required to bundle a copy of the license with your distribution.

---

# Apache 2.0

### Applicable dependencies

* [aiohttp](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/Dependencies/aiohttp): [Link to license](https://github.com/KeepSafe/aiohttp/blob/master/LICENSE.txt)
* [multidict](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/Dependencies/multidict): [Link to license](https://github.com/aio-libs/multidict/blob/master/LICENSE)
* [nacl](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/Dependencies/nacl): [Link to license](https://github.com/pyca/pynacl/blob/master/LICENSE)
* requests ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/kennethreitz/requests/blob/master/LICENSE)

### Relevant quote

>   4\. Redistribution. You may reproduce and distribute copies of the
>      Work or Derivative Works thereof in any medium, with or without
>      modifications, and in Source or Object form, provided that You
>      meet the following conditions:
>
>   (a) You must give any other recipients of the Work or
>        Derivative Works a copy of this License

### Simple translation

* You are required to bundle a copy of the license with your distribution.

# BSD 3-clause

### Applicable dependencies

* colorama ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/tartley/colorama/blob/master/LICENSE.txt)
* pycparser ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/eliben/pycparser/blob/master/LICENSE)
* [opus](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/opus): [Link to license](https://www.opus-codec.org/license/)

### Relevant quote

> \* Redistributions of source code must retain the above copyright notice, this
>   list of conditions and the following disclaimer.
> 
>\* Redistributions in binary form must reproduce the above copyright notice,
>   this list of conditions and the following disclaimer in the documentation
>   and/or other materials provided with the distribution.
>
> \* Neither the name of the copyright holders, nor those of its contributors
>   may be used to endorse or promote products derived from this software without
>   specific prior written permission.

### Simple translation

* You are required to bundle a copy of the license with your distribution.
* You are not allowed to use the names of the contributors to promote your distribution.

# LGPL

### Applicable dependencies

* chardet ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/chardet/chardet/blob/master/LICENSE)
* [ffmpeg](https://github.com/Cheeselab/DecoraterBot/tree/Async-Portable/resources/ffmpeg): [Link to license](https://www.ffmpeg.org/legal.html)

### Relevant quote

> 1\. You may copy and distribute verbatim copies of the Library's
> complete source code as you receive it, in any medium, provided that
> you conspicuously and appropriately publish on each copy an
> appropriate copyright notice and disclaimer of warranty; keep intact
> all the notices that refer to this License and to the absence of any
> warranty; and distribute a copy of this License along with the
> Library.
> 
> [ ... ]
> 
> 4\. You may copy and distribute the Library (or a portion or
> derivative of it, under Section 2) in object code or executable form
> under the terms of Sections 1 and 2 above provided that you accompany
> it with the complete corresponding machine-readable source code, which
> must be distributed under the terms of Sections 1 and 2 above on a
> medium customarily used for software interchange.

### Simple translation

* You are required to bundle a copy of the license with your distribution.
* You must provide the source code of any compiled parts of the libraries, including bytecode-compiled `.pyc` files.

# MIT

### Applicable dependencies

* cffi ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://bitbucket.org/cffi/cffi/src/8ee16fdadf92fe50a70eacbcc3c33eaae10de442/LICENSE?at=default&fileviewer=file-view-default)
* discord.py ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/Rapptz/discord.py/blob/master/LICENSE)
* setuptools/easy_install ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/pypa/setuptools/blob/master/LICENSE)
* six ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://bitbucket.org/gutworth/six/src/ca4580a5a648fc75abc568907e81abc80b05d58c/LICENSE?at=default&fileviewer=file-view-default)

### Relevant quote

> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

### Simple translation

* You are required to bundle a copy of the license with your distribution.

# Unlicense

### Applicable dependencies

* youtube-dl ([Zip](https://github.com/Cheeselab/DecoraterBot/blob/fcdfeb9a62726ea5fe0872c46d18aa6128c81f91/resources/Dependencies/dependencies.zip)): [Link to license](https://github.com/rg3/youtube-dl/blob/master/LICENSE)

### Relevant quote

> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.

### Simple translation

* Do what you want.

---

I was unable to find a license for the following:

* py2pycx (A module for importing packages from the pycx respository automatically)

If you have access to the source repository for this, you should check what license it uses.

---

# The issue with TinyURL

In #11, the following was stated:

> TinyURL3 is mine so I can embed it in here (like you see in my code) just fine

I did a little research on this one as well (Figured I might as well since I looked at everything else), and I found the following issue: Your port is an unattributed derivative work of [this library](https://bitbucket.org/meatballhat/tinyurl/src). The [PyPi page](https://pypi.python.org/pypi/TinyUrl/) for it states that it is under the MIT license, and while your fork [does include this](https://github.com/Cheeselab/TinyURL/blob/master/LICENSE), you haven't provided any attribution to Dan Buch (AKA *meatballhat*), the author of the original. While your claims are otherwise correct, you should attribute Dan in the LICENSE file of your fork.

As this is a clear derivative work (there is a clear structural resemblance between the original code and the fork), the developer cannot simply attribute all of the work to themselves - they also have to provide attribution to the original developer.

It's also worth noting that [the repository](https://bitbucket.org/meatballhat/tinyurl/src) doesn't contain a license, so you have no explicit right to fork the library in the first place - but given that the PyPi page states MIT, it's likely that the author intended to add an MIT license in the first place and forgot - so you should be in the clear. Never hurts to check in, though.

---

# Recommendations

These won't be too painful, I promise.

## If you want to continue distributing your dependencies

For all the licenses, you can do either of the following:

* Create a directory named `licenses`, `attribution`, or something similar, and copy all of the applicable licenses into it, using a filename like `LICENSE-projectname`. For example, for the Opus library, you'd include their copy of the BSD 3-clause license in a file named `LICENSE-opus`.
* Include the relevant LICENSE files along with each of your distributions - For example, for the Opus library, you'd include their copy of the BSD 3-clause license inside your `resources/opus` directory.

For LGPL-licensed libraries only:
* Check whether you're providing the source code for them. If not, you will need to include it - Simply copying the source files along with the compiled files is enough.

## If you'd rather avoid this problem altogether

* Create a `requirements.txt` file that includes the names (and versions if you wish) of all of the PyPi libraries you require.
* Provide instructions for each platform you support on how to install Python, find and install copies of non-PyPi dependencies, and compile dependencies manually that require it. Include links.
* Remove all of the dependencies that you've covered above from the repository, and instruct users to use `python3 -m pip install -U -r requirements.txt` when they install a new instances of your bot, or update an older instance.

---

Do what you want with this information of course - but understand the risks you're undertaking by ignoring licensing issues. For example, [there are](http://sfconservancy.org/copyleft-compliance/) several [organisations that](http://www.fsf.org/licensing/) dedicate themselves to OSS license compliance, and even fund lawsuits relating to them. If you're willing to risk it, then feel free, at that point I'll have done all I can, and the responsibility will fall on the maintainers of this repository.

**Comment by gdude2002** [comment] 2016-09-01 17:00
An archive of this ticket is available at http://archive.is/MJoeh

**Comment by ngbeslhang** [comment] 2016-09-01 18:48
Please tell me you are actually reading this, Ara.

**Comment by macdja38** [comment] 2016-09-01 20:02
I believe my issue https://github.com/Cheeselab/DecoraterBot/issues/15 could solve most of these issues.

**Comment by gdude2002** [comment] 2016-09-01 20:03
Nope, not really.

**Comment by macdja38** [comment] 2016-09-01 20:09
@gdude2002 well, the advantage to the docker approach is you can make a dockerfile that installs all the dependancies, freeing you from the need to include them in teh project.

**Comment by gdude2002** [comment] 2016-09-01 20:10
I don't think this project is likely to move towards a docker-only model. I mean, have you looked at it lately?

**Comment by macdja38** [comment] 2016-09-01 20:11
@gdude2002 I have, and I'm confident it will happen Soon**tm** as outlined by @AraHaan in https://github.com/Cheeselab/DecoraterBot/issues/15

**Comment by gdude2002** [comment] 2016-09-01 20:12
Well, in #11 he claims to have added a proper LICENSE, but we can all see how that went.

Anyway, stop derailing the ticket, please.

**Comment by macdja38** [comment] 2016-09-01 20:16
@gdude2002 I believe I'm suggesting a very real solution to the problems outlined in this ticked.
Problems:
licences are annoying.
Solution:
Create something that installs everything for the user instead of bundling it.

**Comment by AraHaan** [comment] 2016-09-01 20:24
Well 1, I modified discord.py Itself to work differently than Rapptz copy and it says in my copy I am free to redistribute and modify it. And the Files being bytecode in the zips are fine. However its easy to add them in sections in the 1 license file to prevent a overload of files unles put in a folder itself.

**Comment by macdja38** [comment] 2016-09-01 20:26
I'm concered you don't understand that even though you modified it it's still under the origional licence.

**Comment by gdude2002** [comment] 2016-09-01 20:30
Yeah, it's still under the original license - it doesn't matter if you modify it a bit, only the code you wrote is yours. The rest belongs to the original author.

No, the files being bytecode in the zip file is not fine - not if those files are from projects under the LGPL. It's literally in the license.

You're complaining that there might be an overload of files, and yet you include four copies of Python...?

**Comment by AraHaan** [comment] 2016-09-01 20:30
Also py2pycx is a little test API I am trying to code that can compress python script files to 50% less size than their pyc bytecode files.

**Comment by gdude2002** [comment] 2016-09-01 20:31
Do you have a repo for that? I'd be surprised if you're doing that without using gzip/7z and without losing information.

**Comment by AraHaan** [comment] 2016-09-01 20:33
I am using zlib and it works fine with base64 decoding and encoding.

**Comment by gdude2002** [comment] 2016-09-01 20:34
M'kay. Anyway, back [on topic](https://github.com/Cheeselab/DecoraterBot/issues/17#issuecomment-244202415)... Thoughts?

Like, are you just new to software licensing?

**Comment by 2344lkn** [comment] 2016-09-01 20:34
So final conclusion... AraHaan is using Discord.py and is claiming it as his own?

**Comment by AraHaan** [comment] 2016-09-01 20:35
no, I am claming it as modified. big difference

**Comment by AraHaan** [comment] 2016-09-01 20:36
Also I cant seem to get a downloaded copy of the license file it would be different if the python embed copy included a file copy will open up a Python issue Tracker for it.

**Comment by gdude2002** [comment] 2016-09-01 20:37
The `LICENSE` file is here: https://github.com/Rapptz/discord.py/blob/master/LICENSE

Just click the `Raw` button.

**Comment by AraHaan** [comment] 2016-09-01 20:38
oh I found the python one on my clone of 3.6 beta 1. but it should be 100% the same as 3.6 is not released yet.

**Comment by Paladinleeds** [comment] 2016-09-01 20:38
Hi @gdude2002 - I would like to look into this code myself and reconfigure the licensing to ensure everything is covered. Apologies for any inconvenience caused by this.

**Comment by gdude2002** [comment] 2016-09-01 20:38
The LICENSE will be the same, yeah, Danny would have had to have gotten all his contributors to agree to a license change (or a majority at least).

**Comment by gdude2002** [comment] 2016-09-01 20:39
@Paladinleeds Hey, it's all good - you're getting a lot of noise here because someone posted the repo on a Discord server (which is how I found it).

I can see you guys are at least trying to work around this, which is great - It doesn't inconvenience me (I'm not a user) but it's always good to keep things on track.

**Comment by AraHaan** [comment] 2016-09-01 20:44
See dc4d550b3f8996e812f92bd9ffe936b83f5de3d1 for some progress.

**Comment by gdude2002** [comment] 2016-09-01 20:45
Yep, that's good progress.

BTW, put `#17` somewhere in the commit messages and it'll link them to this ticket.

**Comment by Paladinleeds** [comment] 2016-09-01 20:47
Thanks @gdude2002 - I didn't know that was possible (since I am new to GitHub). Duly noted, appreciate the heads up!

**Comment by AraHaan** [comment] 2016-09-01 21:03
I chose including the v3 of the LGPL and the GPL as they are said that the newer ones apply to ffmpeg as well.

**Comment by AraHaan** [comment] 2016-09-01 21:11
Ok, so I had to download the opus sources only to not find a license file in it so I had to open up a source file to it to get it.

**Comment by gdude2002** [comment] 2016-09-01 21:25
The Opus implementation is BSD-3 licensed, the license text is available at the link I gave you (under implementation) - You may want to provide a link to the site at the top of that particular license file

**Comment by AraHaan** [comment] 2016-09-01 21:28
I got 17 currently with the LGPL and the GPL's v3. As stated from theffmpeg site I provided both in case even though I use the exe 30 some MV or so version.

**Comment by AraHaan** [comment] 2016-09-01 21:30
what I could extract for opus in ``opus.c``

    Copyright (c) 2011 Xiph.Org Foundation, Skype Limited
    Written by Jean-Marc Valin and Koen Vos */

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

    - Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

    - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
    OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by gdude2002** [comment] 2016-09-01 21:31
The GPL is LGPL-compatible and covers everything the LGPL does - since you're just providing a statically-compiled binary, you should be safe to just include the GPL if that's what you prefer.

About your snippet: You've recovered a BSD-2 license, but the site clearly says BSD-3. I'd copy the license text from the site, and the copyright header from `opus.c`.

**Comment by AraHaan** [comment] 2016-09-01 21:33
ok

**Comment by gdude2002** [comment] 2016-09-01 21:49
Looks mostly good, you can rename that `gpl` file to match `ffmpeg` as well. You don't need to include the `youtube-dl` one if you want - it's public domain, so you can literally do anything you like with it.

**Comment by jaydenkieran** [comment] 2016-09-01 22:08
Hey, I'd like to add onto this issue that my original issue, #11, isn't necessarily solved. Your license won't really hold up in a court of law. Here's why:

    DecoraterBot's source is protected by Cheese.lab industries Inc. Even though it is Open Source
    any and all users waive the right to say that this bot's code was stolen when it really was not.
    Me @Decorater the only core developer of this bot do not take kindly to those false Allegations.
    it would piss any DEVELOPER OFF WHEN THEY SPEND ABOUT A YEAR CODING STUFF FROM SCRATCH AND THEN BE ACCUSED OF
    CRAP LIKE THIS.

For a start, this is not "legal speak". Infact, a lawyer would look at this and laugh at you. You can't just make users waive the right to freedom of speech. That's literally what you are asking for here.

    So, do not do it. If you do Cheese.lab Industries Inc. Can and Will go after you for such cliams that it deems
    untrue.

These empty threats are also wrong. "Cheese.lab Industries Inc." isn't actually a real incorporated company, unless you'd like to produce the paperwork that outlines this. This is a false statement. You cannot go after someone for saying that they think your work is stolen. That's not how the law works, my friend.

For the next few paragraphs, see [see here](https://github.com/Cheeselab/DecoraterBot/blob/Async-Portable/licenses/LICENSE#L10-L30), this is not correct language to use in a license. This is more of a statement than a license at this point. You're not giving guidelines or conditions on which to use your work.

You need to choose an **actual license** for your project, not just a long winded open letter that seems like the ranting of an 11 year old. There are plenty you can choose from that fits open source projects, and my suggestion is the MIT License.

This website can help you: http://choosealicense.com/

**Comment by gdude2002** [comment] 2016-09-01 22:10
I can vouch for `choosealicense`, it's pretty fantastic.

Everything Jayden says above is true - a real license is invaluable for protecting yourself and your projects. I personally go for BSD-3 or Artistic License 2.0.

It's kind of out of scope of this ticket, and #11 has been re-opened, though. Best continue that there.

**Comment by jaydenkieran** [comment] 2016-09-01 22:13
I've made a comment there with a link to my above comment. I'd suggest moving this project's license discussion over to there as to not hijack this thread - I thought it'd be relevant to continue that argument here since it was along the general topic (and I didn't notice #11 had been re-opened).

**Comment by AraHaan** [comment] 2016-09-01 23:32
@jaydenkieran what I meant by this ``DecoraterBot's source is protected by Cheese.lab industries Inc. Even though it is Open Source
any and all users waive the right to say that this bot's code was stolen when it really was not.`` line is ``No not say that I stole it when I am the original person who developed it.`` And Yes I have reasons as someone litterally tried to say it was theres which I have valid legal proof that I CODED this bot.

**Closed** 2016-09-02 05:24 UTC
Labels: Already in Use, enhancement
